### ISSUE TITLE
[BUG]: The API worker crashes with NoMethodError

### ISSUE THREAD

**Issue by haf** [getlago/lago#185]
**Describe the bug**
The API worker crashes with NoMethodError

```
api-worker-6db955f446-vglsg api-worker I, [2023-01-28T19:11:36.261692 #8]  INFO -- : fail
api-worker-6db955f446-vglsg api-worker W, [2023-01-28T19:11:36.262321 #8]  WARN -- : {"context":"Job raised exception","job":{"retry":0,"queue":"default","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"MigrationTaskJob","args":[{"job_class":"MigrationTaskJob","job_id":"3bef41f4-f9c9-4fab-b5f9-f6aab07d11fd","provider_job_id":null,"queue_name":"default","priority":null,"arguments":["invoices:fill_credit_amount"],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2023-01-28T19:08:22Z","tracing_info":{"membership":null}}],"jid":"b63e123c4d92ace8760887ce","created_at":1674932902.4771295,"enqueued_at":1674933094.7995818},"jobstr":"{\"retry\":0,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"MigrationTaskJob\",\"args\":[{\"job_class\":\"MigrationTaskJob\",\"job_id\":\"3bef41f4-f9c9-4fab-b5f9-f6aab07d11fd\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"invoices:fill_credit_amount\"],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2023-01-28T19:08:22Z\",\"tracing_info\":{\"membership\":null}}],\"jid\":\"b63e123c4d92ace8760887ce\",\"created_at\":1674932902.4771295,\"newrelic\":{},\"enqueued_at\":1674933094.7995818}"}
api-worker-6db955f446-vglsg api-worker W, [2023-01-28T19:11:36.280845 #8]  WARN -- : NoMethodError: undefined method `tail' for nil:NilClass
api-worker-6db955f446-vglsg api-worker
api-worker-6db955f446-vglsg api-worker       @scope = @scope.tail
api-worker-6db955f446-vglsg api-worker                      ^^^^^
api-worker-6db955f446-vglsg api-worker W, [2023-01-28T19:11:36.281509 #8]  WARN -- : /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task_manager.rb:235:in `in_namespace'
api-worker-6db955f446-vglsg api-worker /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/dsl_definition.rb:141:in `namespace'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/tasks/framework.rake:3:in `<main>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `load'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `load'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/tasks.rb:18:in `block in <main>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/tasks.rb:17:in `each'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/tasks.rb:17:in `<main>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:507:in `run_tasks_blocks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:464:in `load_tasks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `public_send'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `method_missing'
api-worker-6db955f446-vglsg api-worker /app/app/jobs/migration_task_job.rb:12:in `perform'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/execution.rb:59:in `block in _perform_job'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/active_job.rb:54:in `perform'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-uniqueness-0.2.4/lib/active_job/uniqueness/active_job_patch.rb:54:in `block (2 levels) in <module:ActiveJobPatch>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/i18n-1.11.0/lib/i18n.rb:322:in `with_locale'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/execution.rb:58:in `_perform_job'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:20:in `_perform_job'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/execution.rb:46:in `perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14:in `block in perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:25:in `block in instrument'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:35:in `instrument'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14:in `perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/logging.rb:18:in `block in perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-traceable-0.3.5/lib/activejob/traceable/logging_patch.rb:17:in `block in tag_logger'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:37:in `tagged'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `tagged'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-traceable-0.3.5/lib/activejob/traceable/logging_patch.rb:17:in `tag_logger'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/logging.rb:18:in `perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sentry-rails-5.3.1/lib/sentry/rails/active_job.rb:6:in `perform_now'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/execution.rb:24:in `block in execute'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72:in `block in wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/execution.rb:22:in `execute'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activejob-7.0.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:196:in `execute_job'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:144:in `block in invoke'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:379:in `perform_action_with_newrelic_trace'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sentry-sidekiq-5.3.1/lib/sentry/sidekiq/sentry_context_middleware.rb:24:in `call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:146:in `block in invoke'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/middleware/chain.rb:149:in `invoke'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:163:in `block in process'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/job_retry.rb:115:in `local'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/rails.rb:14:in `block in call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72:in `block in wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71:in `wrap'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/rails.rb:13:in `call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:257:in `stats'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/job_logger.rb:13:in `call'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/job_retry.rb:82:in `global'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/job_logger.rb:39:in `prepare'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:123:in `dispatch'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:162:in `process'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:78:in `process_one'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/processor.rb:68:in `run'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:8:in `watchdog'
api-worker-6db955f446-vglsg api-worker /usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**To Reproduce**
1. Start the whole system at commits pointed to by https://github.com/getlago/lago/commit/93c49b24052942f6a162b91bf4f1e017b44cce10 and specifically this version of the lago container: `getlago/api:v0.20.0-beta`

**Expected behavior**
For an empty installation there should be no errors or crashes.

**Screenshots**

**Support**
 - OS: macOS / docker
 - Version: v0.20.0-beta
 - 
Container setup:

```yaml
      containers:
      - name: api-worker
        image: getlago/api:v0.20.0-beta
        args:
        - ./scripts/start.worker.sh
```

**Comment by jdenquin** [comment]
Hello @haf , thanks for pointing it, looking at it.
btw you can update to the `v0.21.0-beta` that contains news features and some fixes!

**Comment by jdenquin** [comment]
Hello @haf,

Apparently you have a `migration_job` that is failing for a strange reason.
I tried to reproduce it without any success on the `v0.20.0-beta`. Do you still have the problem after a whole restart?

**Comment by haf** [comment]
No repro in latest version.
