### ISSUE TITLE
[BUG]: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by CMiksche** [getlago/lago#190]
**Describe the bug**
I tried different configuration options but always get the following error from the Frontend:

```
Access to fetch at 'https://my.api.url/graphql' from origin 'https://my.front.url' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

If I try to open the backend, I get a 502 HTTP Error - but I suppose that is normal because I don't call the API with a Key right?

**To Reproduce**
1. I setup the current version after the documentation with the current docker images
2. I set custom env vars for the frontend url, api url, frontend port and backend port
3. I also configured my Webserver (Caddy) as a reverse proxy for the two domains
4. After starting the containers I get the mentioned error on the frontend

**Expected behavior**

I expected no CORS error to happen because my URLs are defined in the ENV variables.

**Support**
 - OS: I use Ubuntu 22.04.1 LTS on the Server
 - Browser: All (I primarily use Chrome and Safari)
 - Version: v0.22.1-beta, but also tested with v0.22.0-beta

**Additional context**

- I use a ssl cert from caddy and configured both urls with https in the env vars.
- I don't use docker but podman instead. (This shouldn't be a problem - most docker apps I use work without any problem with podman)
- It might be connected to problems with PostgreSQL. I tried to use my hostsystem PostgreSQL first but failed because somehow the connection out of the container didn't work but then switched to the PostgreSQL container instead but for that I needed to change the outbound port because of my Hostsystem PostgreSQL instance.

**Comment by mathieu-lago** [comment]
Hi @CMiksche - thanks for the clear description!

Our engineering team will review your ticket and get back to you with an update on Monday.

**Comment by jdenquin** [comment]
Hello @CMiksche 

Did you set up the env var `LAGO_FRONT_URL` for the `api` container? It sounds like the api does not know your used url.
It should be `export LAGO_FRONT_URL=my.api.url` in this case.

https://doc.getlago.com/docs/guide/self-hosting/docker#environment-variables

**Comment by CMiksche** [comment]
> Did you set up the env var `LAGO_FRONT_URL` for the `api` container?

Yes. I set up `LAGO_FRONT_URL`, `FRONT_PORT`, `LAGO_API_URL`, `API_PORT`, `POSTGRES_DB`, `POSTGRES_USER`, `POSTGRES_PASSWORD`, `POSTGRES_PORT`, `LAGO_ENCRYPTION_PRIMARY_KEY`, `LAGO_ENCRYPTION_DETERMINISTIC_KEY`, `LAGO_ENCRYPTION_KEY_DERIVATION_SALT`, `SECRET_KEY_BASE` and `LAGO_RSA_PRIVATE_KEY`.

All of these env vars are available when I check it with e.g. `echo "$LAGO_FRONT_URL"`

> It should be `export LAGO_FRONT_URL=my.api.url` in this case.

Shouldn't it be `https://my.front.url` in the example case? I have a different URL (lets say `https://my.front.url` for the frontend then I have for the backend - e.g. `https://my.api.url`)

**Comment by jdenquin** [comment]
For the `api` env var `LAGO_FRONT_URL` it should be the domain only, without `https`

**Comment by CMiksche** [comment]
> For the `api` env var `LAGO_FRONT_URL` it should be the domain only, without `https`

If I remove the `https://`, the following message appears in the console: `POST https://my.front.url/my.api.url/graphql 405`

So the `https://` seems to be necessary because otherwise it doesn't make a right resolution.

And in the [documentation](https://doc.getlago.com/docs/guide/self-hosting/docker#configuration) it is also written with the HTTP-Protocol: `http://localhost` (and that's also the default value in the docker-compose.yml file in this repo)

**Comment by CMiksche** [comment]
There is also this Error:

```
rails aborted!
URI::InvalidURIError: bad URI(is not URI?): "https://license.getlago.com/verify/${LAGO_LICENSE:-}"
/app/lib/lago_http_client/lago_http_client/client.rb:10:in `initialize'
/app/lib/lago_utils/lago_utils/license.rb:13:in `new'
/app/lib/lago_utils/lago_utils/license.rb:13:in `verify'
/app/config/initializers/license.rb:7:in `<main>'
/app/config/environment.rb:7:in `<main>'
```

What's this `LAGO_LICENSE` and why isn't in mentioned in the documentation?

**Comment by jdenquin** [comment]
> > For the `api` env var `LAGO_FRONT_URL` it should be the domain only, without `https`
> 
> If I remove the `https://`, the following message appears in the console: `POST https://my.front.url/my.api.url/graphql 405`

Sorry, my bad, I was checking for your `development`environment that uses only domain, you have to use the `https://`, we actually use it this way for our cloud environment!
Since the `LAGO_FRONT_URL` is defined you should not have the CORS issue, I don't know if it can comes from `podman` but I do not see any reasons why.

Could you launch a terminal on the `api` container and do a `export $LAGO_FRONT_URL` into it just to double check that it's present?


> > What's this LAGO_LICENSE and why isn't in mentioned in the documentation?
`LAGO_LICENSE` is not into the documentation since it's only for our `premium` users, if you do not set a `LAGO_LICENSE` env var you should not have this error, I will check how podman is managing env var, there should be a problem around this, with a standard docker usage, the `LICENSE` error is not showing up.

**Comment by CMiksche** [comment]
> Could you launch a terminal on the `api` container and do a `export $LAGO_FRONT_URL` into it just to double check that it's present?

The `lago-api` container with the `start` script seems to automatically stop after setting everything up, so I unfortunately can't `attach` into it. Is this normal or should it continue to run?

The container based on the `api` image with the `worker` script returns the following after running `attach`:

```
W, [2023-02-15T12:03:34.486525 #2]  WARN -- : Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)
W, [2023-02-15T12:03:34.487193 #2]  WARN -- : /usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:398:in `rescue in establish_connection'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:379:in `establish_connection'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:115:in `block in connect'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:344:in `with_reconnect'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:114:in `connect'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:25:in `block in connect'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:10:in `block in connect_with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:55:in `block in with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:55:in `with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:10:in `connect_with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:25:in `connect'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:417:in `ensure_connected'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:269:in `block in process'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:356:in `logging'
/usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:78:in `block in logging'
/usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:17:in `block in instrument'
/usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:28:in `record_span'
/usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:16:in `instrument'
/usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:77:in `logging'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:268:in `process'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/client.rb:161:in `call'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:17:in `block in call'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:17:in `block in call_with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:55:in `block in with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:55:in `with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:17:in `call_with_tracing'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:17:in `call'
/usr/local/bundle/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
/usr/local/bundle/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
/usr/local/bundle/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
/usr/local/bundle/gems/redis-4.7.1/lib/redis/commands/server.rb:90:in `info'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq.rb:180:in `block in redis_info'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq.rb:156:in `block in redis'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq.rb:153:in `redis'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq.rb:174:in `redis_info'
/usr/local/bundle/gems/sidekiq-6.5.1/lib/sidekiq/cli.rb:75:in `run'
/usr/local/bundle/gems/sidekiq-6.5.1/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

When I actually check if `$LAGO_FRONT_URL` is present, the worker returns the right URL.

Maybe a bit more on how I set it up:

- The `API_PORT` is set to `3001` and then I use caddy to assign a domain with it (caddy also provides the SSL-Cert):

```
my.api.url {
    reverse_proxy localhost:3001
}
```

- The `FRONT_PORT` is set to `8081` and I also use the same structure with caddy:

```
my.front.url {
    reverse_proxy localhost:8081
}
```

I can also `ping` the `$LAGO_FRONT_URL` from the `worker` container, so the network connection seem to work...

**Comment by CMiksche** [comment]
> The container based on the `api` image with the `worker` script returns the following after running `attach`:

This problem was because `podman` doesn't support DNS networking out of the box, so containers can't resolve each other by name... I could fix it by enabling the DNS plugin... Now the containers can talk to the redis container...

Unfortunately the CORS error is still there...

**Comment by CMiksche** [comment]
Here are the logs from the `lago-api` container before it stopped:

```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
2023-02-15T14:36:24.755912956+01:00 rake aborted!
2023-02-15T14:36:24.757993603+01:00 URI::InvalidURIError: bad URI(is not URI?): "https://license.getlago.com/verify/${LAGO_LICENSE:-}"
2023-02-15T14:36:24.758471110+01:00 /app/lib/lago_http_client/lago_http_client/client.rb:10:in `initialize'
2023-02-15T14:36:24.758471110+01:00 /app/lib/lago_utils/lago_utils/license.rb:13:in `new'
2023-02-15T14:36:24.758471110+01:00 /app/lib/lago_utils/lago_utils/license.rb:13:in `verify'
2023-02-15T14:36:24.758471110+01:00 /app/config/initializers/license.rb:7:in `<main>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
2023-02-15T14:36:24.758471110+01:00 /app/config/environment.rb:7:in `<main>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:348:in `require_environment!'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:511:in `block in run_tasks_blocks'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/bin/bundle:25:in `load'
2023-02-15T14:36:24.758471110+01:00 /usr/local/bundle/bin/bundle:25:in `<main>'
2023-02-15T14:36:24.760356235+01:00 Tasks: TOP => db:migrate => db:load_config => environment
2023-02-15T14:36:24.760450970+01:00 (See full trace by running task with --trace)
2023-02-15T14:36:27.260315988+01:00 rails aborted!
2023-02-15T14:36:27.260448134+01:00 URI::InvalidURIError: bad URI(is not URI?): "https://license.getlago.com/verify/${LAGO_LICENSE:-}"
2023-02-15T14:36:27.260558710+01:00 /app/lib/lago_http_client/lago_http_client/client.rb:10:in `initialize'
2023-02-15T14:36:27.260558710+01:00 /app/lib/lago_utils/lago_utils/license.rb:13:in `new'
2023-02-15T14:36:27.260558710+01:00 /app/lib/lago_utils/lago_utils/license.rb:13:in `verify'
2023-02-15T14:36:27.260558710+01:00 /app/config/initializers/license.rb:7:in `<main>'
2023-02-15T14:36:27.260558710+01:00 /app/config/environment.rb:7:in `<main>'
2023-02-15T14:36:27.260619503+01:00 Tasks: TOP => signup:seed_organization => environment
2023-02-15T14:36:27.260647684+01:00 (See full trace by running task with --trace)
2023-02-15T14:36:28.974532503+01:00 => Booting Puma
2023-02-15T14:36:28.974532503+01:00 => Rails 7.0.4 application starting in production 
2023-02-15T14:36:28.974532503+01:00 => Run `bin/rails server --help` for more startup options
2023-02-15T14:36:29.259502347+01:00 Exiting
2023-02-15T14:36:29.260079400+01:00 /usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:67:in `split'2023-02-15T14:36:29.260251760+01:00 : 2023-02-15T14:36:29.260343971+01:00 bad URI(is not URI?): "https://license.getlago.com/verify/${LAGO_LICENSE:-}"2023-02-15T14:36:29.260437175+01:00  (2023-02-15T14:36:29.260527462+01:00 URI::InvalidURIError2023-02-15T14:36:29.260577004+01:00 )2023-02-15T14:36:29.260615787+01:00 
2023-02-15T14:36:29.260652785+01:00 	from /usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:72:in `parse'
2023-02-15T14:36:29.260705994+01:00 	from /usr/local/lib/ruby/3.1.0/uri/common.rb:188:in `parse'
2023-02-15T14:36:29.260751148+01:00 	from /usr/local/lib/ruby/3.1.0/uri/common.rb:692:in `URI'
2023-02-15T14:36:29.260806732+01:00 	from /app/lib/lago_http_client/lago_http_client/client.rb:10:in `initialize'
2023-02-15T14:36:29.260875909+01:00 	from /app/lib/lago_utils/lago_utils/license.rb:13:in `new'
2023-02-15T14:36:29.260913911+01:00 	from /app/lib/lago_utils/lago_utils/license.rb:13:in `verify'
2023-02-15T14:36:29.260952803+01:00 	from /app/config/initializers/license.rb:7:in `<main>'
2023-02-15T14:36:29.260989551+01:00 	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
2023-02-15T14:36:29.261046197+01:00 	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
2023-02-15T14:36:29.261085129+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
2023-02-15T14:36:29.261124231+01:00 	from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
2023-02-15T14:36:29.261160048+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
2023-02-15T14:36:29.262197436+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
2023-02-15T14:36:29.262229125+01:00 	from /app/config/environment.rb:7:in `<main>'
2023-02-15T14:36:29.262229125+01:00 	from config.ru:3:in `require_relative'
2023-02-15T14:36:29.262229125+01:00 	from config.ru:3:in `block in <main>'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/builder.rb:116:in `eval'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/builder.rb:116:in `new_from_string'
2023-02-15T14:36:29.262229125+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/builder.rb:105:in `load_file'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/builder.rb:66:in `parse_file'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:249:in `app'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:422:in `wrapped_app'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:312:in `block in start'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:379:in `handle_profiling'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/rack-2.2.6.2/lib/rack/server.rb:311:in `start'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
2023-02-15T14:36:29.262249001+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
2023-02-15T14:36:29.262249001+01:00 	from <internal:kernel>:90:in `tap'
2023-02-15T14:36:29.262259942+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
2023-02-15T14:36:29.262259942+01:00 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
2023-02-15T14:36:29.262259942+01:00 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
2023-02-15T14:36:29.262259942+01:00 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
2023-02-15T14:36:29.262259942+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
2023-02-15T14:36:29.262269500+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
2023-02-15T14:36:29.262269500+01:00 	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
2023-02-15T14:36:29.262269500+01:00 	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2023-02-15T14:36:29.262269500+01:00 	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2023-02-15T14:36:29.262269500+01:00 	from bin/rails:4:in `<main>'
```

**Comment by jdenquin** [comment]
Oh Okay I see, your api is not running so thats why it's not working!
The worker can't connect to your redis, is it accessible from your pod?

You have an error around the `LAGO_LICENSE` because your env var is defined to `${LAGO_LICENSE:-}`, it should be null actually (empty)
