### ISSUE TITLE
[BUG]: Address family not supported by protocol - socket(2) for "::" port 3000 (Errno::EAFNOSUPPORT) on docker-compose up

### ISSUE THREAD

**Issue by vibl** [getlago/lago#231]
**Describe the bug**
After following the install instructions (`docker-compose up`), all containers start but the lago-api logs go on a loop with the following error message:

```
lago-api      | W, [2023-05-01T10:46:41.536364 #8]  WARN -- : `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/app/config/initializers/sidekiq.rb:21:in `<main>'", "/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'"]
lago-api      | W, [2023-05-01T10:46:42.651615 #10]  WARN -- : `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/app/config/initializers/sidekiq.rb:21:in `<main>'", "/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'"]
lago-api      | => Booting Puma
lago-api      | => Rails 7.0.4.3 application starting in production 
lago-api      | => Run `bin/rails server --help` for more startup options
lago-api      | W, [2023-05-01T10:46:43.575241 #11]  WARN -- : `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/app/config/initializers/sidekiq.rb:21:in `<main>'", "/usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'"]
lago-api      | Puma starting in single mode...
lago-api      | * Puma version: 5.6.4 (ruby 3.2.2-p53) ("Birdie's Version")
lago-api      | *  Min threads: 5
lago-api      | *  Max threads: 5
lago-api      | *  Environment: production
lago-api      | *          PID: 11
lago-api      | Exiting
lago-api      | /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:341:in `initialize': Address family not supported by protocol - socket(2) for "::" port 3000 (Errno::EAFNOSUPPORT)
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:341:in `new'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:341:in `add_tcp_listener'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:173:in `block in parse'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:156:in `each'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/binder.rb:156:in `parse'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/runner.rb:156:in `load_and_bind'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
lago-api      |         from /usr/local/bundle/gems/puma-5.6.4/lib/rack/handler/puma.rb:72:in `run'
lago-api      |         from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/server.rb:327:in `start'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:38:in `start'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
lago-api      |         from <internal:kernel>:90:in `tap'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:134:in `perform'
lago-api      |         from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
lago-api      |         from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
lago-api      |         from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
lago-api      |         from /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
lago-api      |         from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
lago-api      |         from /usr/local/bundle/gems/boo
``` 

**Support**
 - OS: Kubuntu 22.04

**Comment by vibl** [comment]
Solved: I had to reactivate ipv6 on my system.
