### ISSUE TITLE
[BUG]: Error while trying to deserialize arguments: Couldn't find PaymentProviderCustomers::StripeCustomer with 'id'

### ISSUE THREAD

**Issue by dmitry8912** [getlago/lago#276]
Lago fails to send a checkout url when connecting exising customer to Stripe first time.

1. Create new customer at Lago
2. Create new customer at Stripe
3. Set lago_customer_id and customer_id to the Stripe customer
4. Set Payment provider customer ID to the lago customer and save
5. At first attempt to set up Payment provider customer ID job that generates checkout url and delivers customer.checkout_url_generated webhook will fail

**Expected behavior**
Webhook customer.checkout_url_generated works fine

**Support**
 - Version v0.44.1-beta

**Log messages**
From lago-worker

```
I, [2023-08-24T15:14:46.029675 #7]  INFO -- : start
E, [2023-08-24T15:14:46.033840 #7] ERROR -- : [ActiveJob] [PaymentProviderCustomers::StripeCheckoutUrlJob] [c903925c-509f-4406-bb2c-da3a546ba43c] [membership/406191ee-7e12-44bc-a0a8-b003790a812d] Error performing PaymentProviderCustomers::StripeCheckoutUrlJob (Job ID: c903925c-509f-4406-bb2c-da3a546ba43c) from Sidekiq(providers) in 3.37ms: ActiveJob::DeserializationError (Error while trying to deserialize arguments: Couldn't find PaymentProviderCustomers::StripeCustomer with 'id'=ef9dc4fa-6874-4ba1-8488-f50370a3b252 [WHERE "payment_provider_customers"."type" = $1]):
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:381:in `raise_record_not_found_exception!'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:475:in `find_one'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:457:in `find_with_ids'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:69:in `find'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/querying.rb:22:in `find'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/core.rb:271:in `find'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:129:in `locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `block in locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `block in unscoped'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation.rb:881:in `_scoping'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation.rb:428:in `scoping'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/scoping/default.rb:43:in `unscoped'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `unscoped'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:16:in `locate'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:148:in `deserialize_global_id'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:132:in `deserialize_argument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `block in deserialize'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `map'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `deserialize'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/core.rb:190:in `deserialize_arguments'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/core.rb:180:in `deserialize_arguments_if_needed'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:44:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:25:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:35:in `instrument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `block in perform_now'
/usr/local/bundle/gems/activejob-traceable-0.4.1/lib/activejob/traceable/logging_patch.rb:17:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/activejob-traceable-0.4.1/lib/activejob/traceable/logging_patch.rb:17:in `tag_logger'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `perform_now'
/usr/local/bundle/gems/sentry-rails-5.3.1/lib/sentry/rails/active_job.rb:6:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:24:in `block in execute'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:22:in `execute'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:209:in `execute_job'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:177:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:25:in `block in call'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:383:in `perform_action_with_newrelic_trace'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:20:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/sentry-sidekiq-5.3.1/lib/sentry/sidekiq/sentry_context_middleware.rb:7:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/metrics/tracking.rb:26:in `track'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/metrics/tracking.rb:122:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:176:in `block in process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_retry.rb:113:in `local'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/rails.rb:16:in `block in call'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/rails.rb:15:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:270:in `stats'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_retry.rb:80:in `global'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:128:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_logger.rb:39:in `prepare'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:127:in `dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:175:in `process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:82:in `process_one'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:72:in `run'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/component.rb:10:in `watchdog'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/component.rb:19:in `block in safe_thread'
I, [2023-08-24T15:14:46.034656 #7]  INFO -- : Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job 5baeef35675e5ef0494ad272
I, [2023-08-24T15:14:46.039681 #7]  INFO -- : fail
W, [2023-08-24T15:14:46.039779 #7]  WARN -- : {"context":"Job raised exception","job":{"retry":0,"queue":"providers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"PaymentProviderCustomers::StripeCheckoutUrlJob","args":[{"job_class":"PaymentProviderCustomers::StripeCheckoutUrlJob","job_id":"c903925c-509f-4406-bb2c-da3a546ba43c","provider_job_id":null,"queue_name":"providers","priority":null,"arguments":[{"_aj_globalid":"gid://lago-api/PaymentProviderCustomers::StripeCustomer/ef9dc4fa-6874-4ba1-8488-f50370a3b252"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2023-08-24T15:14:46Z","tracing_info":{"membership":"membership/406191ee-7e12-44bc-a0a8-b003790a812d"}}],"jid":"5baeef35675e5ef0494ad272","created_at":1692890086.0289314,"enqueued_at":1692890086.0290048},"_config":"#<Sidekiq::Config:0x00007f29d038f788>"}
W, [2023-08-24T15:14:46.039806 #7]  WARN -- : ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find PaymentProviderCustomers::StripeCustomer with 'id'=ef9dc4fa-6874-4ba1-8488-f50370a3b252 [WHERE "payment_provider_customers"."type" = $1]
W, [2023-08-24T15:14:46.039847 #7]  WARN -- : /usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:381:in `raise_record_not_found_exception!'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:475:in `find_one'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:457:in `find_with_ids'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/finder_methods.rb:69:in `find'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/querying.rb:22:in `find'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/core.rb:271:in `find'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:129:in `locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `block in locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `block in unscoped'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation.rb:881:in `_scoping'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation.rb:428:in `scoping'
/usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/scoping/default.rb:43:in `unscoped'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `unscoped'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `locate'
/usr/local/bundle/gems/globalid-1.1.0/lib/global_id/locator.rb:16:in `locate'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:148:in `deserialize_global_id'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:132:in `deserialize_argument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `block in deserialize'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `map'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/arguments.rb:43:in `deserialize'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/core.rb:190:in `deserialize_arguments'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/core.rb:180:in `deserialize_arguments_if_needed'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:44:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:25:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:35:in `instrument'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `block in perform_now'
/usr/local/bundle/gems/activejob-traceable-0.4.1/lib/activejob/traceable/logging_patch.rb:17:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/activejob-traceable-0.4.1/lib/activejob/traceable/logging_patch.rb:17:in `tag_logger'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `perform_now'
/usr/local/bundle/gems/sentry-rails-5.3.1/lib/sentry/rails/active_job.rb:6:in `perform_now'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:24:in `block in execute'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:22:in `execute'
/usr/local/bundle/gems/activejob-7.0.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:209:in `execute_job'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:177:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:25:in `block in call'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:383:in `perform_action_with_newrelic_trace'
/usr/local/bundle/gems/newrelic_rpm-8.15.0/lib/new_relic/agent/instrumentation/sidekiq/server.rb:20:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/sentry-sidekiq-5.3.1/lib/sentry/sidekiq/sentry_context_middleware.rb:7:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/metrics/tracking.rb:26:in `track'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/metrics/tracking.rb:122:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:176:in `block in process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_retry.rb:113:in `local'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/rails.rb:16:in `block in call'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/rails.rb:15:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:270:in `stats'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_retry.rb:80:in `global'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:128:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/job_logger.rb:39:in `prepare'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:127:in `dispatch'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:175:in `process'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:82:in `process_one'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/processor.rb:72:in `run'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/component.rb:10:in `watchdog'
/usr/local/bundle/gems/sidekiq-7.0.8/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

**Comment by michaelponrajah** [comment]
Hey @dmitry8912 

From what I can see on your breakdown, you mentioned those steps:

1. Create new customer at Lago
2. Create new customer at Stripe
3. Set lago_customer_id and customer_id to the Stripe customer
4. Set Payment provider customer ID to the lago customer and save
5. At first attempt to set up Payment provider customer ID job that generates checkout url and delivers customer.checkout_url_generated webhook will fail

Have you set up the connection Stripe <> Lago in your Settings > Integrations before doing 1st step? 👀

**Comment by dmitry8912** [comment]
@michaelponrajah hi!
Of course, the integration setup steps was performed.
I forget to say that everything works fine when i use Lago API for creating customers with those parameters:
sync: true,
syncWithProvider: true.

Bug repoduces only in case when i try to link existing lago customer (who has never been connected to payment provider) and exising stripe customer.

**Comment by jdenquin** [comment]
@dmitry8912 it seems that Lago does not find your stripe customer, can you check that it exists into your database?
