### ISSUE TITLE
[BUG]: Error when running docker compose

### ISSUE THREAD

**Issue by TudorAndrei** [getlago/lago#332]
**Describe the bug**
When running docker-compose up i get the following error:
```
ERROR: Invalid interpolation format for "healthcheck" option in service "api-worker": "bundle exec sidekiqmon | grep $(hostname) || exit 1"
```
**To Reproduce**
1. Follow the installation guide
2. Run `docker compose up`

**Expected behavior**
All the services should have started.

**Screenshots**
![image](https://github.com/getlago/lago/assets/25133006/03639a49-3af4-4f16-9697-5c2bec797f8b)

**Support**
 - OS: linux
 - Browser [e.g. chrome, safari] - not applicable
 - Version [e.g. 22] - commit 4e5defc846eb49941aae9d1a49642242e0dc4935

**Comment by reboottime** [comment]
Yeah, I'm having the same issue

**Comment by jdenquin** [comment]
can you comment the line https://github.com/getlago/lago/blob/main/docker-compose.yml#L136 and give it a try again?

**Comment by TudorAndrei** [comment]
that worked, now I get this error on the `lago-worker`, the worker keeps restarting, and on localhost:3000 the page is blank

```
bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- sprockets/railtie (LoadError)
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /app/config/environments/development.rb:4:in `<main>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/engine.rb:562:in `block (2 levels) in <class:Engine>'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/engine.rb:561:in `each'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/engine.rb:561:in `block in <class:Engine>'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `each'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
	from /app/config/environment.rb:7:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:303:in `boot_application'
	from /usr/local/bundle/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:42:in `run'
	from /usr/local/bundle/gems/sidekiq-7.1.4/bin/sidekiq:31:in `<top (required)>'
	from /usr/local/bundle/bin/sidekiq:25:in `load'
	from /usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
	```

**Comment by jdenquin** [comment]
can you put `RAILS_ENV=production` ?

**Comment by TudorAndrei** [comment]
I have managed to the the self hosted instance up and running, apparently the L136 was different in my case and I had commented the RAILS_ENV.

It works now and I can't wait to get it up and running.

**Comment by ionosphere** [comment]
Hi,
I ve the same error now.

I think that you could replace your healtcheck by curl command.

```yml
healthcheck:
      test: ["CMD-SHELL", "curl localhost:3000"]
```

**Comment by ramirobg94** [comment]
> Hi, I ve the same error now.
> 
> I think that you could replace your healtcheck by curl command.
> 
> ```yaml
> healthcheck:
>       test: ["CMD-SHELL", "curl localhost:3000"]
> ```

On the `api-worker:` at the `docker-composer.yml`
